serviceAccount:
  create: false
  name: fluent-bit

cloudWatch:
  enabled: true
  region: us-east-1
  logGroupName: /eks/project-bedrock/application
  logStreamPrefix: retail-

firehose:
  enabled: false

kinesis:
  enabled: false

elasticsearch:
  enabled: false